project:
  type: website
  output-dir: docs
  
website:
  title: "Rx-CHaR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
  page-footer:
    right: "Morpho Initiative, NCEAS"
    left: "2024"

format:
  html:
    theme: cerulean
    toc: true

editor: source

